### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by arzoo7** [morrmarco/Ivey-Hack-The-Case#1]
Hi,

Can you please help me reset my password as I do not remember it and have forgotten some of my security question answers as well.

**Comment by cindyzhong** [comment]
Hi, what is your username?

**Comment by jstaf** [comment]
The security questions are not actually used for resetting passwords right now. (I turned that off in favor of it sending you an email.) 

Click the "forgot password" link, enter your username and email, and it'll send an email to the email address you registered at. Click the link in the email twice, and it'll take you to the page where you can reset your password.

Note that the `tempxxxx` accounts are not resettable.

**Comment by morrmarco** [comment]
Only one forgotten password.  I am happy with that.  
Thanks for your response Jeff and Cindy

**Comment by arzoo7** [comment]
Thanks all for your replies.
My username is : ic034
I am still being redirected to the security questions page and did not receive an email to reset my password after I proceeded with "forgot password".

Can you please help?

**Comment by jstaf** [comment]
The email would have been sent to your xxxxxxx.msc2019@ivey.ca email address. Alternatively, you can send me an email at jeff.stafford@queensu.ca and I'll reset it for you. (Admittedly I can't address things directly here, since this issue tracker is publicly viewable.)

**Comment by arzoo7** [comment]
Thanks @jstaf .
I did not get any email still.
Will inbox you now.
