### ISSUE TITLE
Full Data Set Customer Details

### ISSUE THREAD

**Issue by s2barcla** [morrmarco/Ivey-Hack-The-Case#6]
Hi there,

We are looking at the full data sets. From the customer detail and quality activity table, age_class and hasActivity cannot be found. When we try to query using proc sql, the log says that "the following columns were not found in the contributing tables". When joining tables using that variable, the log also reports an error. However, when we look at the table in the SAS file we created from the csv, the columns are there in their appropriate tables. Is this a data error?

Thank you!

**Comment by morrmarco** [comment]
that is a better idea

**Comment by s2barcla** [comment]
Sorry for the delay! Here is the code: 

proc sql;
select age_class from sceneful.customerdetail  where gender = 'Male';
quit

And here is the error message:

1          OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
 72         
 73         proc sql;
 74         select age_class from sceneful.customerdetail  where gender = 'Male';
 ERROR: The following columns were not found in the contributing tables: age_class.

Thank you!

**Comment by s2barcla** [comment]
Thank you so Cindy!! It was a 'Type'n variable. We've got it working now!

**Comment by s2barcla** [comment]
Hi Cindy,

We actually ran into another issue.

We followed your instructions and checked the code that created the sas table, it looks as follows:

PROC SQL;
CREATE TABLE WORK.query AS
SELECT Unique_member_identifier , City , StateProv , FSA , PointsTotal , LanguagePreference , gender , 'age_class'n 
FROM SCENEFUL.CUSTOMERDETAIL;
RUN;
QUIT;

However, when trying to use that format to query age_class, it stills shows the same error in the log:

proc sql;
select "age_class"n from sceneful.customerdetail  where gender = 'Male';
quit;

 Log Error
 1          OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
 72         
 73         
 74         options VALIDMEMNAME=EXTEND;
 75         proc sql;
 76         select "age_class"n from sceneful.customerdetail  where gender = 'Male';
 ERROR: The following columns were not found in the contributing tables: age_class.

Second Question:

where i import the csv file into SAS, sometimes one column will have a missing value and then the value from next column will be filled into it. Please refer to row 14186.How do I avoid that?


![log](https://user-images.githubusercontent.com/38298521/38769884-1e0a2d1c-3fd8-11e8-894c-2efb9a0bace6.png)

**Comment by cindyzhong** [comment]
Hi,
Did you create the csv file in Excel? 

My suggestion is to open the csv file in a text editor (for example, notepad++), check if there is any formatting issue with the csv file. Because when you open a csv in Excel and then save it as csv, it may cause a problem. Make sure your csv is actually a valid csv, eg. when it is empty, it's actually separated by a comma.
Also, when you open your csv file in text editor, you can change the heading so it only contains letters, clean up the heading a bit.

Cindy

**Comment by cindyzhong** [comment]
Also, 
try running the query exactly as it is and see if you are able to run it.

PROC SQL;
CREATE TABLE WORK.query AS
SELECT Unique_member_identifier , City , StateProv , FSA , PointsTotal , LanguagePreference , gender , 'age_class'n
FROM SCENEFUL.CUSTOMERDETAIL;
RUN;
QUIT;

**Comment by cindyzhong** [comment]
Hi,
I took a look at the source data.
Looks like the file has some unicode issue.
@jstaf Any ideas on how we can help?
Tried to load the first 15000 lines in jupyter also gives me unicode error.
<img width="737" alt="screen shot 2018-04-14 at 10 29 22 pm" src="https://user-images.githubusercontent.com/14058067/38774336-4fde0b2c-4034-11e8-9ecc-205c04b7e2b1.png">

**Comment by jstaf** [comment]
So I had a happy discovery a few days ago that you can actually get R to try to guess the encodings of a given file (don't think there's a Python equivalent, but who knows). It'll tell you which encoding it thinks the file is, with a set of probabilities for each guess.

In an R command prompt somewhere:
```r
> library(tidyverse)
> guess_encoding('mystery_file.csv')
# A tibble: 2 x 2
  encoding   confidence
  <chr>           <dbl>
1 ISO-8859-1      0.420
2 ISO-8859-2      0.290
```

**Comment by cindyzhong** [comment]
@s2barcla  Like Jeff has said, the file is encoded in ISO 8859.
Use the code sample attached to Import the CSV file, then you will be able to select the age_class column.
`/** FOR CSV Files uploaded from Unix/MacOS **/
FILENAME CSV "/home/czhong/small_custdetail_raw.csv" encoding='ISO-8859-1' 
	TERMSTR=LF;

/** Import the CSV file.  **/
data WORK.MYCSV;
	%let _EFIERR_ = 0;

	/* set the ERROR detection macro variable */
	infile CSV delimiter=',' MISSOVER DSD firstobs=2;
	informat Unique_member_identifier $36.;
	informat City $16.;
	informat StateProv $2.;
	informat FSA $3.;
	informat PointsTotal best32.;
	informat LanguagePreference $7.;
	informat gender $6.;
	informat age_class $6.;
	format Unique_member_identifier $36.;
	format City $16.;
	format StateProv $2.;
	format FSA $3.;
	format PointsTotal best32.;
	format LanguagePreference $7.;
	format gender $6.;
	format age_class $6.;
	input Unique_member_identifier  $
                  City  $
                  StateProv  $
                  FSA PointsTotal LanguagePreference  $
                  gender  $
                  age_class  $;

	if _ERROR_ then
		call symputx('_EFIERR_', 1);

	/* set ERROR detection macro variable */
run;

PROC SQL;
	CREATE TABLE TEST AS SELECT age_class FROM MYCSV;
QUIT;
`
For any other ISO 8859 file, you can also modify the sample code to import it.

**Comment by cindyzhong** [comment]
@s2barcla  Like Jeff has said, the file is encoded in ISO 8859.
Use the code sample to Import the CSV file, then you will be able to select the age_class column.

FILENAME CSV "/home/czhong/small_custdetail_raw.csv" encoding='ISO-8859-1' 
	TERMSTR=LF;

/** Import the CSV file.  **/
data WORK.MYCSV;
	%let _EFIERR_ = 0;
	infile CSV delimiter=',' MISSOVER DSD firstobs=2;
	informat Unique_member_identifier $36.;
	informat City $16.;
	informat StateProv $2.;
	informat FSA $3.;
	informat PointsTotal best32.;
	informat LanguagePreference $7.;
	informat gender $6.;
	informat age_class $6.;
	format Unique_member_identifier $36.;
	format City $16.;
	format StateProv $2.;
	format FSA $3.;
	format PointsTotal best32.;
	format LanguagePreference $7.;
	format gender $6.;
	format age_class $6.;
	input Unique_member_identifier  $
                  City  $
                  StateProv  $
                  FSA PointsTotal LanguagePreference  $
                  gender  $
                  age_class  $;
	if _ERROR_ then
		call symputx('_EFIERR_', 1);
run;

PROC SQL;
	CREATE TABLE TEST AS SELECT age_class FROM MYCSV;
QUIT;

For any other ISO 8859 file, you can also modify the sample code to import it.

**Comment by s2barcla** [comment]
Thank you so much Cindy and Jeff!! That was very informative in helping us solve our problem :)
